// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnClickSystem.Infrastructure.Data;

#nullable disable

namespace OnClickSystem.Migrations
{
    [DbContext(typeof(OnClickContext))]
    [Migration("20260121151306_CriandoFinanceiro")]
    partial class CriandoFinanceiro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnClickSystem.Models.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Associado_Responsavel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Associado_Responsavel");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("OnClickSystem.Models.Comissao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Beneficiario")
                        .HasColumnType("int");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Beneficiario");

                    b.HasIndex("ID_Pedido");

                    b.ToTable("Comissoes");
                });

            modelBuilder.Entity("OnClickSystem.Models.ConfiguracaoComissao", b =>
                {
                    b.Property<int>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nivel"));

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Nivel");

                    b.ToTable("ConfiguracaoComissao");
                });

            modelBuilder.Entity("OnClickSystem.Models.Kit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Kits");
                });

            modelBuilder.Entity("OnClickSystem.Models.LogSistema", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LogsSistema");
                });

            modelBuilder.Entity("OnClickSystem.Models.Pedido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("ID_Kit")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Cliente");

                    b.HasIndex("ID_Kit");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("OnClickSystem.Models.Transacao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("OnClickSystem.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ID_Patrocinador")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Patrocinador");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OnClickSystem.Models.Cliente", b =>
                {
                    b.HasOne("OnClickSystem.Models.Usuario", "Associado")
                        .WithMany()
                        .HasForeignKey("ID_Associado_Responsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associado");
                });

            modelBuilder.Entity("OnClickSystem.Models.Comissao", b =>
                {
                    b.HasOne("OnClickSystem.Models.Usuario", "Beneficiario")
                        .WithMany()
                        .HasForeignKey("ID_Beneficiario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnClickSystem.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiario");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("OnClickSystem.Models.Pedido", b =>
                {
                    b.HasOne("OnClickSystem.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ID_Cliente");

                    b.HasOne("OnClickSystem.Models.Kit", "Kit")
                        .WithMany()
                        .HasForeignKey("ID_Kit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnClickSystem.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario");

                    b.Navigation("Cliente");

                    b.Navigation("Kit");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OnClickSystem.Models.Usuario", b =>
                {
                    b.HasOne("OnClickSystem.Models.Usuario", "Patrocinador")
                        .WithMany("Indicados")
                        .HasForeignKey("ID_Patrocinador");

                    b.Navigation("Patrocinador");
                });

            modelBuilder.Entity("OnClickSystem.Models.Usuario", b =>
                {
                    b.Navigation("Indicados");
                });
#pragma warning restore 612, 618
        }
    }
}
